[package]
name = "subranges"
version = "0.3.0"
authors = ["f3kilo <f3kilo@yandex.ru>"]
edition = "2021"
repository = "https://github.com/F3kilo/subrange"
description = "Library to manage non-interssecting integer intervals"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
